### PR TITLE
Make module compatible with 4.4-dev.5

### PR DESCRIPTION
**Pull request by timoschwarzer**
In 4.4, Godot aligned some of the internal method names with the exposed ones. I also fixed a few instances where the compat macros weren't used. Compiles successfully on and works with the current master branch of Godot.

(also thanks for making this! :heart: )

### CODE REVIEW

**Comment by timoschwarzer** [comment]
If you don't want to merge this before the release of 4.4, I'll keep the `4.4-compat` branch updated until then :+1:

**Comment by limbonaut** [comment]
**Rubonnek** keeps #223 updated, which is synchronized with the `master` (I think).
We'll have a release most likely (or two) before 4.4 is out, so 4.3.x remains the main target right now. Check https://github.com/limbonaut/limboai/pull/223#discussion_r1773204150. I need to document our process (tracked by #247).

**Comment by timoschwarzer** [comment]
I should have checked for an existing PR haha :laughing:

**Comment by limbonaut** [comment]
No worries, thanks for the initiative!

**Pull request closed without merging**
